version: "3.8"

services:
  python:
    build: ./python
    environment:
      MINIO_ACCESS_KEY:
      MINIO_SECRET_KEY:
    volumes:
      - ./python/src:/usr/src/app
      - ./python/files:/tmp
    depends_on:
      - minio

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY:
      MINIO_SECRET_KEY:
    ports:
      - "9000:9000"
    volumes:
      - ./minio/data:/data
    command: server /data